version: '2'
services:
  nginx:
    image: nginx
    volumes:
      - ./:/app:delegated
      - ./docker/nginx/:/etc/nginx/conf.d/
    ports:
      - '10080:80'
  php:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    environment:
      YII_DEBUG: 'true'
      YII_ENV: 'dev'
      YII_MAIL_FILE_TRANSPORT: 'true'
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./:/app:delegated